# Generated by Django 5.2.7 on 2025-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
