# Generated by Django 5.2.7 on 2025-10-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_api', '0002_checkin_latitude_checkin_longitude'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
